/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExpressionStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AnonymousUser = IDL.Principal;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ModerationStatus = IDL.Variant({
  'unchecked' : IDL.Null,
  'safe' : IDL.Null,
  'unsafe' : IDL.Null,
});
export const EmpathyType = IDL.Variant({
  'silentPresence' : IDL.Null,
  'mirroring' : IDL.Null,
  'reflection' : IDL.Null,
  'listening' : IDL.Null,
});
export const Expression = IDL.Record({
  'id' : IDL.Text,
  'status' : ExpressionStatus,
  'creator' : AnonymousUser,
  'createdAt' : Time,
  'audioBlobId' : ExternalBlob,
  'updatedAt' : Time,
  'moderationStatus' : ModerationStatus,
  'empathyType' : EmpathyType,
});
export const Response = IDL.Record({
  'id' : IDL.Text,
  'responder' : AnonymousUser,
  'createdAt' : Time,
  'expressionId' : IDL.Text,
  'audioBlobId' : ExternalBlob,
  'updatedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignRandomExpression' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Expression)],
      [],
    ),
  'getAvailableExpressions' : IDL.Func([], [IDL.Vec(Expression)], ['query']),
  'getExpression' : IDL.Func([IDL.Text], [IDL.Opt(Expression)], ['query']),
  'getResponse' : IDL.Func([IDL.Text], [IDL.Opt(Response)], ['query']),
  'moderateExpression' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'respondToExpression' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'reviewAndAssign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'uploadExpression' : IDL.Func([ExternalBlob, EmpathyType], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExpressionStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AnonymousUser = IDL.Principal;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ModerationStatus = IDL.Variant({
    'unchecked' : IDL.Null,
    'safe' : IDL.Null,
    'unsafe' : IDL.Null,
  });
  const EmpathyType = IDL.Variant({
    'silentPresence' : IDL.Null,
    'mirroring' : IDL.Null,
    'reflection' : IDL.Null,
    'listening' : IDL.Null,
  });
  const Expression = IDL.Record({
    'id' : IDL.Text,
    'status' : ExpressionStatus,
    'creator' : AnonymousUser,
    'createdAt' : Time,
    'audioBlobId' : ExternalBlob,
    'updatedAt' : Time,
    'moderationStatus' : ModerationStatus,
    'empathyType' : EmpathyType,
  });
  const Response = IDL.Record({
    'id' : IDL.Text,
    'responder' : AnonymousUser,
    'createdAt' : Time,
    'expressionId' : IDL.Text,
    'audioBlobId' : ExternalBlob,
    'updatedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignRandomExpression' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Expression)],
        [],
      ),
    'getAvailableExpressions' : IDL.Func([], [IDL.Vec(Expression)], ['query']),
    'getExpression' : IDL.Func([IDL.Text], [IDL.Opt(Expression)], ['query']),
    'getResponse' : IDL.Func([IDL.Text], [IDL.Opt(Response)], ['query']),
    'moderateExpression' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'respondToExpression' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'reviewAndAssign' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'uploadExpression' : IDL.Func([ExternalBlob, EmpathyType], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };