/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnonymousUser = Principal;
export type EmpathyType = { 'silentPresence' : null } |
  { 'mirroring' : null } |
  { 'reflection' : null } |
  { 'listening' : null };
export interface Expression {
  'id' : string,
  'status' : ExpressionStatus,
  'creator' : AnonymousUser,
  'createdAt' : Time,
  'audioBlobId' : ExternalBlob,
  'updatedAt' : Time,
  'moderationStatus' : ModerationStatus,
  'empathyType' : EmpathyType,
}
export type ExpressionStatus = { 'assigned' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export type ModerationStatus = { 'unchecked' : null } |
  { 'safe' : null } |
  { 'unsafe' : null };
export interface Response {
  'id' : string,
  'responder' : AnonymousUser,
  'createdAt' : Time,
  'expressionId' : string,
  'audioBlobId' : ExternalBlob,
  'updatedAt' : Time,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignRandomExpression' : ActorMethod<[Principal], [] | [Expression]>,
  'getAvailableExpressions' : ActorMethod<[], Array<Expression>>,
  'getExpression' : ActorMethod<[string], [] | [Expression]>,
  'getResponse' : ActorMethod<[string], [] | [Response]>,
  'moderateExpression' : ActorMethod<[string, boolean], undefined>,
  'respondToExpression' : ActorMethod<[string, ExternalBlob], string>,
  'reviewAndAssign' : ActorMethod<[string, boolean], undefined>,
  'uploadExpression' : ActorMethod<[ExternalBlob, EmpathyType], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];